package com.yuan.common.core.exception.workflow;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum WorkflowErrorCode {
    //规则： WF_{域}_{语义}
    //WF：workflow 模块前缀
    //{域}：TASK / INSTANCE / NODE / ENGINE / DEFINITION / PERMISSION / VARIABLE
    //{语义}：ALREADY_HANDLED / NOT_FOUND / ILLEGAL_STATE / NO_PERMISSION

    // ===== Task =====
    WF_TASK_NOT_FOUND("WF_TASK_NOT_FOUND", "任务不存在"),
    WF_TASK_ALREADY_HANDLED("WF_TASK_ALREADY_HANDLED", "任务已处理"),
    WF_TASK_NO_PERMISSION("WF_TASK_NO_PERMISSION", "无权操作该任务"),
    WF_TASK_NOT_ASSIGNEE("WF_TASK_NOT_ASSIGNEE", "当前用户不是任务处理人"),
    WF_TASK_STATUS_INVALID("WF_TASK_STATUS_INVALID", "任务状态不合法"),
    WF_TASK_ALREADY_TRANSFERRED("WF_TASK_ALREADY_TRANSFERRED", "任务已转交"),
    WF_TASK_CANNOT_TRANSFER("WF_TASK_CANNOT_TRANSFER", "当前任务不允许转交"),
    WF_TASK_CANNOT_DELEGATE("WF_TASK_CANNOT_DELEGATE", "当前任务不允许委派"),
    WF_TASK_NOT_TODO("WF_TASK_NOT_TODO", "任务不是待办状态"),
    WF_TASK_ASSIGNEE_EMPTY("WF_TASK_ASSIGNEE_EMPTY", "任务未指派处理人"),

    // ===== Task Log=====
    WF_TASK_LOG_FAITH("WF_TASK_LOG_FAITH", "保存任务日志失败"),

    // ===== Instance =====
    WF_INSTANCE_NOT_FOUND("WF_INSTANCE_NOT_FOUND", "流程实例不存在"),
    WF_INSTANCE_ALREADY_FINISHED("WF_INSTANCE_ALREADY_FINISHED", "流程实例已结束"),
    WF_INSTANCE_ALREADY_CANCELED("WF_INSTANCE_ALREADY_CANCELED", "流程实例已撤销"),
    WF_INSTANCE_STATUS_INVALID("WF_INSTANCE_STATUS_INVALID", "流程实例状态不合法"),
    WF_INSTANCE_CANNOT_WITHDRAW("WF_INSTANCE_CANNOT_WITHDRAW", "当前流程不允许撤销"),
    WF_INSTANCE_NOT_STARTER("WF_INSTANCE_NOT_STARTER", "只有发起人可以执行该操作"),
    WF_INSTANCE_NEXT_NO_ERROR("WF_INSTANCE_NEXT_NO_ERROR", "获取节点序列号失败"),

    // ===== Node / Activity =====
    WF_NODE_NOT_FOUND("WF_NODE_NOT_FOUND", "流程节点不存在"),
    WF_NODE_NOT_USER_TASK("WF_NODE_NOT_USER_TASK", "目标节点不是用户任务"),
    WF_NODE_NOT_REACHABLE("WF_NODE_NOT_REACHABLE", "目标节点不可达"),
    WF_NODE_ALREADY_COMPLETED("WF_NODE_ALREADY_COMPLETED", "目标节点已完成"),
    WF_NODE_STATUS_INVALID("WF_NODE_STATUS_INVALID", "节点状态不合法"),
    WF_NODE_TYPE_INVALID("WF_NODE_TYPE_INVALID", "节点类型不合法"),
    WF_NODE_CONCURRENT_CHANGED("WF_NODE_CONCURRENT_CHANGED", "节点已经被处理"),

    WF_ROLLBACK_TARGET_INVALID("WF_ROLLBACK_TARGET_INVALID", "退回目标节点不合法"),
    WF_ROLLBACK_TO_FUTURE_NODE("WF_ROLLBACK_TO_FUTURE_NODE", "不允许退回到后续节点"),
    WF_ROLLBACK_SAME_NODE("WF_ROLLBACK_SAME_NODE", "不能退回到当前节点"),
    WF_ROLLBACK_NOT_ALLOWED("WF_ROLLBACK_NOT_ALLOWED", "当前节点不允许退回"),

    // ===== Permission =====
    WF_PERMISSION_DENIED("WF_PERMISSION_DENIED", "无操作权限"),
    WF_OPERATOR_NOT_FOUND("WF_OPERATOR_NOT_FOUND", "操作人不存在"),
    WF_OPERATOR_NOT_CANDIDATE("WF_OPERATOR_NOT_CANDIDATE", "当前用户不是候选人"),
    WF_OPERATOR_NOT_ASSIGNEE("WF_OPERATOR_NOT_ASSIGNEE", "当前用户不是处理人"),
    WF_OPERATOR_NOT_ADMIN("WF_OPERATOR_NOT_ADMIN", "当前用户不是管理员"),

    // ===== Definition / Parser =====
    WF_DEFINITION_NOT_FOUND("WF_DEFINITION_NOT_FOUND", "流程定义不存在"),
    WF_DEFINITION_INVALID("WF_DEFINITION_INVALID", "流程定义不合法"),
    WF_DEFINITION_PARSE_ERROR("WF_DEFINITION_PARSE_ERROR", "流程定义解析失败"),
    WF_DEFINITION_NO_START_NODE("WF_DEFINITION_NO_START_NODE", "流程未配置开始节点"),
    WF_DEFINITION_NO_END_NODE("WF_DEFINITION_NO_END_NODE", "流程未配置结束节点"),
    WF_DEFINITION_DUPLICATE_NODE("WF_DEFINITION_DUPLICATE_NODE", "流程定义存在重复节点"),
    WF_DEFINITION_NO_DEFAULT_GATEWAY("WF_DEFINITION_NO_DEFAULT_GATEWAY", "网关节点未命中任何条件，且未配置默认分支"),
    WF_DEFINITION_NODE_NOT_FOUND("WF_DEFINITION_NODE_NOT_FOUND", "节点不存在"),

    // ===== Engine / Runtime =====
    WF_ENGINE_ERROR("WF_ENGINE_ERROR", "流程引擎异常"),
    WF_ENGINE_ILLEGAL_STATE("WF_ENGINE_ILLEGAL_STATE", "流程引擎状态异常"),
    WF_ENGINE_EXECUTION_NOT_FOUND("WF_ENGINE_EXECUTION_NOT_FOUND", "执行实例不存在"),
    WF_ENGINE_CONCURRENT_MODIFICATION("WF_ENGINE_CONCURRENT_MODIFICATION", "流程并发冲突"),
    WF_ENGINE_STATE_TRANSITION_INVALID("WF_ENGINE_STATE_TRANSITION_INVALID", "非法的状态迁移"),

    // ===== Variable / Expression =====
    WF_VARIABLE_NOT_FOUND("WF_VARIABLE_NOT_FOUND", "流程变量不存在"),
    WF_VARIABLE_TYPE_MISMATCH("WF_VARIABLE_TYPE_MISMATCH", "流程变量类型不匹配"),
    WF_VARIABLE_REQUIRED("WF_VARIABLE_REQUIRED", "流程变量不能为空"),
    WF_EXPRESSION_EVALUATE_ERROR("WF_EXPRESSION_EVALUATE_ERROR", "条件表达式计算失败"),

    // ===== biz ===== 已存在
    WF_BIZ_ALREADY_EXISTS("WF_BIZ_ALREADY_EXISTS", "该申请已提交，请勿重复提交"),
    WF_BIZ_NOT_FOUND("WF_BIZ_NOT_FOUND", "该业务不存在流程关联"),

    //============ ai ==========
    WF_AI_EXECUTE_FAIL("WF_AI_EXECUTE_FAIL", "AI节点审核失败");
    private final String code;
    private final String defaultMessage;
}
